version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3.8.16-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: ["CMD", "rabbitmqctl", "await_online_nodes", "1"]
      interval: 5s
      timeout: 300s
      retries: 3
      start_period: 60s
